pfDB = {
  ["areatrigger"] = {},
  ["items"] = {},
  ["meta"] = {},
  ["meta-tbc"] = {},
  ["meta-wotlk"] = {},
  ["minimap"] = {},
  ["minimap-tbc"] = {},
  ["minimap-wotlk"] = {},
  ["objects"] = {},
  ["professions"] = {},
  ["quests"] = {},
  ["quests-itemreq"] = {},
  ["refloot"] = {},
  ["units"] = {},
  ["zones"] = {},
}
